server:
  port: 8081
  servlet:
    context-path: /contents

spring:
  application:
    name: security-server
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/spring-security?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ywh169747
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

security:
  oauth2:
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8080/oauth/token
      user-authorization-uri: http://localhost:8080/oauth/authorize
    resource:
      token-info-uri: http://localhost:8080/oauth/check_token

mybatis:
  type-aliases-package: com.springboot.springsecurity.resource.domain
  mapper-locations: classpath:mybatis/mapper/*.xml