spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/quartz?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ywh169747
    type: com.zaxxer.hikari.HikariDataSource

mybatis-plus:
  type-aliases-package: com.springboot.quartz.entity
  mapper-locations: classpath*:/mybatis/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    # Âß¼­É¾³ý
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0
