configs:
  com:
    yanwenhui:
      redis:
        redisson:
          dynamic:
            enable: true
          oneRedisson:
            singleServerConfigExt:
              address: redis://139.196.228.154:6380
#              password: 123456
              database: 1
          twoRedisson:
            singleServerConfigExt:
              address: redis://139.196.228.154:6380
#              password: 123456
              database: 2
