server:
  port: 8081
  servlet:
    context-path: /admin-client

spring:
  application:
    name: spring-boot-admin-client
  cloud:
    nacos:
      discovery:
        group: spring-boot-admin
        metadata:
          management:
            context-path: ${server.servlet.context-path}/actuator
      server-addr: 39.100.31.158:8848
      username: nacos
      password: nacos
#  boot:
#    admin:
#      notify:
#        pagerduty:
#          client-url: http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
